# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_password'),
        ('posts', '0004_auto_20200319_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
            preserve_default=False,
        ),
    ]
