# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, upload_to='news_image'),
        ),
        migrations.AddField(
            model_name='news',
            name='image3',
            field=models.ImageField(blank=True, upload_to='news_image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to='news_image'),
            preserve_default=False,
        ),
    ]
