# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200401_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='forum_thread',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
