# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-05 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_forum_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='forum_thread',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(choices=[('N', 'News'), ('U', 'Updates'), ('F', 'FNN')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
