# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200409_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newscomments', to='news.News'),
        ),
    ]
