# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-29 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='password',
            new_name='favourite_character',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_quote',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_series',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
