# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200329_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cosplay_image1',
            field=models.ImageField(default='default.jpg', upload_to='cosplay_pic'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cosplay_image2',
            field=models.ImageField(default='default.jpg', upload_to='cosplay_pic'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cosplay_input',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_quote',
            field=models.TextField(max_length=400),
        ),
    ]
