# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-20 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200320_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
