# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cosplay_image3',
            field=models.ImageField(default=1, upload_to='cosplay_pic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='cosplay_image1',
            field=models.ImageField(default='no-cosplay-img.jpg', upload_to='cosplay_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cosplay_image2',
            field=models.ImageField(upload_to='cosplay_pic'),
        ),
    ]
