# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200401_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cosplay_image2',
            field=models.ImageField(blank=True, upload_to='cosplay_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cosplay_image3',
            field=models.ImageField(blank=True, upload_to='cosplay_pic'),
        ),
    ]
