# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-04 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200404_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Since you are new here, you could introduce yourself. This page servers exactly this purpose. Here you can introduce yourself to users who visits you profile!', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cosplay_input',
            field=models.TextField(default='If you like to dress like you favourite character, you can show it here!', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_character',
            field=models.CharField(default='Everyone', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_quote',
            field=models.TextField(default='Live long and prosper!', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourite_series',
            field=models.CharField(default='All of them', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='New user', max_length=40),
        ),
    ]
