# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='image',
        ),
        migrations.AddField(
            model_name='games',
            name='image1',
            field=models.ImageField(default=1, upload_to='games_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='image2',
            field=models.ImageField(default=1, upload_to='games_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='image3',
            field=models.ImageField(default=1, upload_to='games_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='image4',
            field=models.ImageField(default=1, upload_to='games_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='image5',
            field=models.ImageField(default=1, upload_to='games_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='link',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
