# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200402_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('1', 'Clothing'), ('2', 'Accesories'), ('3', 'Drinkware'), ('4', 'Home & Office'), ('5', 'Collectibles')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
